import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import AppRight from "./components/AppRight";

export default function Home() {
  return (
    <div className="flex">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          background:
            "url(https://cutewallpaper.org/21/mount-everest-hd-wallpaper/40-Mountain-Sunset-4K-Wallpapers-Download-at-WallpaperBro.jpg)",
          flex: "0.6",
        }}
        className="font-poppins flex flex-col h-screen justify-center items-center !bg-cover !bg-bottom object-contain rounded-r-3xl "
      >
        <h2 className="absolute top-10 left-10 text-xl font-bold text-white">
          TooTravel
        </h2>
        <div className="flex flex-col w-3/5">
          <h1 className="text-white text-5xl font-semibold">
            The most beautiful places in the world!
          </h1>
          <p className="text-white text-sm mt-10">
            {" "}
            Plan your vacation on the most beautiful places in the world
          </p>
          <button className="bg-orange w-60 text-[#fff] h-10 mt-10 py-2 px-5 rounded-xl hover:bg-[#8a3413] hover:scale-110 transition duration-500">
            Get Started
          </button>
        </div>
        <div className="absolute bottom-20 left-40 flex items-center hover:scale-110 duration-700">
          <p className="text-white mr-2">01</p>
          <div className="h-[2px] w-8 bg-white mr-2"></div>
          <div className="h-[2px] w-8 bg-white bg-opacity-20 mr-2 hover:bg-opacity-100 cursor-pointer"></div>
          <div className="h-[2px] w-8 bg-white bg-opacity-20 mr-2 hover:bg-opacity-100 cursor-pointer"></div>
          <p className="text-white mr-2">03</p>
        </div>
      </div>
      <div style={{ flex: "0.4" }}>
        <AppRight></AppRight>
        <div className="absolute bottom-2 right-80 text-center justify-center items-center">
          <p className="text-blue text-1xl font-semibold">
            {" "}
            Developed by Eslam Turki
          </p>
        </div>
      </div>
    </div>
  );
}
